on:
  schedule:
    - cron:  '0 12 * * 1-5'
  push: ~
  pull_request: ~
name: Test
jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - run: |
          docker build -t ci .
